server:
  port: 0

spring:
  application:
    name: user-auth-service
  config:
    import: "optional:configserver:http://localhost:7788"
  profiles:
    active: auth-local
  main:
    banner-mode: console
  http:
    multipart:
      max-file-size: '10MB'
      max-request-size: '11MB'

encrypt:
  key: zadpooh-deep-night-swpark

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7766/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true


