spring:
  application:
    name: user-auth-service
  config:
    import: "optional:configserver:http://localhost:7788"
  profiles:
    active: user-local
  main:
    banner-mode: console

encrypt:
  key: zadpooh-deep-night-swpark

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7766/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

server:
  port: 0

