server:
  port: 7788

spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zadpooh/spring.cloud.application.suite.git
          search-paths: config/**
          default-label: master

encrypt:
  key: zadpooh-deep-night-swpark

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7766/eureka/
#      defaultZone: http://discovery:7766/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name} # metric 정보에 대한 라벨링 설정