server:
  port: 7733

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
#      discovery:
#        locator:
#          lower-case-service-id: true
#          enabled: true
      routes:
        - id: demo-service
          uri: lb://DEMO-SERVICE
          predicates:
            - Path=/api/demo/**
          filters:
            - RewritePath=/api/demo/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins:
#              - "http://localhost:7272"
#            allow-credentials: true
#            allowedHeaders: '*'
#            allowedMethods:
#              - PUT
#              - GET
#              - POST
#              - DELETE
#              - OPTIONS

springdoc:
  swagger-ui:
    urls[0]:
      name: demo-service
      url: http://localhost:${server.port}/v3/api-docs/demo-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7766/eureka/
#      defaultZone: http://discovery:7766/eureka/

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name} # metric 정보에 대한 라벨링 설정
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": ${server.port}

