spring:
  http:
    multipart:
      max-file-size: '10MB'
      max-request-size: '11MB'

logging:
  file:
    name: 'D:/storage/logs/tomcat/user/application.log'
  pattern:
    file: 'D:/storage/logs/tomcat/user/application.log.%d{yyyy-MM-dd}'

